### ISSUE TITLE
How to ignore python virtual environment?

### ISSUE THREAD

**Issue by amritpurshotam** [bvobart/mllint#30]
My virtual environment is stored in in my project in a directory called `env`. `mllint` doesn't seem to ignore this and I can't find a configuration to exclude it. This results in a very slow analysis and it gives me suggestions for all of my dependencies and drowns out anything to do with my project

**Comment by bvobart** [comment]
`mllint` does ignore virtualenvs by default, but assumes that they are in the standard `.venv` or `venv` folders, not `env`.

Since this is the second issue posted about this so far, it might actually be useful to add a configuration option for additional virtualenv dirs to ignore.

**Comment by amritpurshotam** [comment]
Ah I see, but great thanks!
If the official GitHub Python `.gitignore` is anything to go on, you could use all the environment listed there https://github.com/github/gitignore/blob/master/Python.gitignore#L107

**Comment by bvobart** [comment]
Good source, thanks! I didn't know `env` and `.env` were also valid standardised virtualenv locations, I thought that was only `venv` and `.venv`. Much easier to just add those directly.

**Comment by bvobart** [comment]
Fixed in 7e2a29d 

Release of `mllint` v0.12.1 is underway :)
