### ISSUE TITLE
No wheel package for Python 3.10

### ISSUE THREAD

**Issue by Cornul11** [bvobart/mllint#34]
In a Python 3.10 environment, it is impossible to install `mllint` and `pip` downloads the source package only which respectively fails. Considering the project's current state, the build from source is not correctly set up for such situations.

**Comment by bvobart** [comment]
Hi, thanks for reporting this issue. The last time I committed to this repo, Python 3.10 did not yet exist, so no wheel package could be created for it yet. I must also note that this project is now no longer maintained, but I will fix the builds once I am able to.

Unfortunately, I don't have my laptop with me right now and I cannot fix it from my phone, so I am not able to fix it at the moment. When I get back to it in two weeks, I will fix the issue and fix the source package too so it has the binaries for all major OS'es.

**Comment by Cornul11** [comment]
No worries. I reported this issue simply because on pypi it is stated that it's compatible with Python 3.10. 
And indeed, I have fixed it simply by using Python 3.8.

**Comment by bvobart** [comment]
Hi, I've finally gotten around to fixing this. v0.12.2 is being deployed right now, which will be deployed with a wheel, as well as a Docker container for Python v3.10. I've also made the source package include all of the compiled `mllint` binaries, so it should now keep working for future Python versions to come.
